import Head from "next/head";
import Footer from "./Footer";
import Header from "./Header";



const MainLayout = ({ children }) => {
    return (
        <>
            <Head>
                <title>Events App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main>{children}</main>
            <Footer />
        </>
    );
};

export default MainLayout;