import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link';


const inter = Inter({ subsets: ['latin'] })

export default function Home({ events_categories }) {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <header><nav>
          <Link href="/" passHref>Home</Link>
          <Link href="/events" passHref>Events</Link>
          <Link href="/about-us" passHref>About</Link>
        </nav></header>
        <section>
          <h1>Events</h1>
          {events_categories.map(e => <div key={e.id}><Link href={`/events/${e.id}`} passHref>
            <Image src={e.image} alt='An Image' width={600} height={400} />
            <h2>{e.title}</h2>
            <p>{e.description}</p>
          </Link></div>)}
          {/* <div><Link href='/events/new-york'>
            <h2>Event in New York</h2>
            <p>Suspendisse ligula elit, viverra tempor mi eu, hendrerit semper lorem. Nam finibus nulla at arcu posuere malesuada. Praesent sollicitudin lectus leo, ac rhoncus eros tristique vel. Pellentesque eu magna id metus dignissim aliquam quis eu lorem. Sed sit amet mi laoreet, varius turpis et, pulvinar nisi. Sed lobortis volutpat ipsum tristique faucibus. Donec ornare justo Link ligula egestas malesuada. Nam vitae nulla eu nibh hendrerit condimentum non sed ligula. Fusce aliquet nunc magna, vel malesuada tortor sollicitudin quis. Donec vulputate quam ex, ut lacinia lectus iaculis vitae. </p>
          </Link></div>
          <div><Link href='/events/san-fransisco'>
            <h2>Event in San Francisco</h2>
            <p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Quisque sapien odio, vestibulum id rutrum quis, pulvinar nec diam. Nulla vitae sapien tincidunt, malesuada turpis quis, rutrum nisl. Sed aliquam vitae ante Link mattis. Aliquam ac orci sodales, convallis tortor nec, aliquet metus. Maecenas mattis turpis at odio tristique venenatis. Praesent cursus ac justo in finibus. Quisque ultricies turpis at dui accumsan suscipit. Mauris congue luctus sapien at lobortis.</p>
          </Link></div>
          <div><Link href='/events/london'>
            <h2>Event in London</h2>
            <p>Quisque Link dui tristique, ullamcorper felis in, dapibus odio. Morbi varius neque in aliquet ullamcorper. Fusce sed elit eros. Nulla volutpat hendrerit ante, sit amet elementum quam molestie ac. In hac habitasse platea dictumst. Phasellus pharetra iaculis mi sit amet convallis. Sed eu nisl non mi efficitur eleifend vel non dui. Praesent vehicula nibh metus, quis lobortis ligula ultrices at. In purus velit, tristique at eros ut, pharetra consectetur elit.</p>
          </Link></div> */}
        </section>
      </main >
      <footer>
        <p>&copy; 2023 Muzammil-cyber</p>
      </footer>
    </>
  )
}

export async function getServerSideProps(context) {
  const { events_categories } = await import('/data/data.json');
  return {
    props: { events_categories }
  };
}
